module Generators

using Genie

const model_name = "AppModel"

function mvcfolders()
  isdir(Genie.config.path_initializers) || mkpath(Genie.config.path_initializers)
  isdir(Genie.config.path_plugins) || mkdir(Genie.config.path_plugins)
  isdir("controllers") || mkdir("controllers")
  isdir("layouts") || mkdir("layouts")
  isdir("models") || mkdir("models")
  isdir("views") || mkdir("views")
end

function logging()
  mvcfolders()
  isfile(joinpath(Genie.config.path_initializers, "logging.jl")) && return
  open(joinpath(Genie.config.path_initializers, "logging.jl"), "w") do io
    write(io,
    """
    import Genie
    Genie.Logger.initialize_logging()
    """
    )
  end
end

function autoload()
  mvcfolders()
  isfile(joinpath(Genie.config.path_initializers, "autoload.jl")) && return
  open(joinpath(Genie.config.path_initializers, "autoload.jl"), "w") do io
    write(io,
    """
    # Optional flat/non-resource MVC folder structure
    Genie.Loader.autoload(abspath("models"), abspath("controllers"))
    """
    )
  end
end

function layout()
  isfile(joinpath("layouts", "app.jl.html")) && return

  open(joinpath("layouts", "app.jl.html"), "w") do io
    write(io,
    raw"""
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <% Stipple.sesstoken() %>
        <title>Hello Genie</title>
        <% Genie.Assets.favicon_support() %>
        <link rel="stylesheet" href="$(Genie.Configuration.basepath())/css/autogenerated.css">
        <link rel="stylesheet" href="$(Genie.Configuration.basepath())/css/app.css">
      </head>
      <body>
        <% page(model, partial = true, [@yield]) %>
        <script src="/js/app.js"></script>
      </body>
    </html>
    """
    )
  end
end

function model()
  isfile(joinpath("models", "$(model_name)s.jl")) && return

  open(joinpath("models", "$(model_name)s.jl"), "w") do io
    write(io,
    """
    module $(model_name)s

    using Stipple

    export $(model_name)

    @reactive mutable struct $(model_name) <: ReactiveModel
      message::R{String} = "Hello World!"
    end

    function handlers(model::$(model_name)) :: $(model_name)
      #=
      on(model.message) do message
        model.isprocessing = true
        model.message[] = "Hello to you too!"
        model.isprocessing = false
      end
      =#

      model
    end

    end
    """
    )
  end
end

function assets()
  isdir(Genie.config.server_document_root) || mkdir(Genie.config.server_document_root)

  if ! isfile(joinpath(Genie.config.server_document_root, "css", "app.css"))
    open(joinpath(Genie.config.server_document_root, "css", "app.css"), "w") do io
      write(io,
      """
      /* place your custom css here */
      """
      )
    end
  end

  if ! isfile(joinpath(Genie.config.server_document_root, "css", "autogenerated.css"))
    open(joinpath(Genie.config.server_document_root, "css", "autogenerated.css"), "w") do io
      write(io,
      """
      /* WARNING!!! */
      /* This CSS file is generated by GenieBuilder. */
      /* Do not edit this file directly or you'll lose all your changes. */
      """
      )
    end
  end

  if ! isfile(joinpath(Genie.config.server_document_root, "js","app.js"))
    open(joinpath(Genie.config.server_document_root, "js", "app.js"), "w") do io
      write(io,
      """
      /* place your custom js here */
      """
      )
    end
  end
end

function view()
  isfile("app.jl.html") && return

  open("app.jl.html", "w") do io
    write(io,
    """
    <h4> Hello Genie! </h4>
    <p> Generated {{N}} random numbers. </p>
    <p v-text="msg"></p>
    <q-slider v-model="N" :label="true"></q-slider>
    <p>This is the default view for the application.</p>
    <p>You can change this view by editing the file <code>app.jl.html</code>.</p>
    """
    )
  end
end

function app()
  isfile("app.jl") && return

  open("app.jl", "w") do io
    write(io,
    """
    module App
    # set up Genie development environmet
    using GenieFramework
    @genietools

    # add your data analysis code
    function mean(x)
        sum(x) / length(x)
    end

    # add reactive code to make the UI interactive
    @app begin
        # reactive variables are tagged with @in and @out
        @in N = 0
        @out msg = "The average is 0."
        # @private defines a non-reactive variable
        @private result = 0.0

        # watch a variable and execute a block of code when
        # its value changes
        @onchange N begin
            # the values of result and msg in the UI will
            # be automatically updated
            result = mean(rand(N))
            msg = "The average is \$result."
        end
    end

    # register a new route and the page that will begin
    # loaded on access
    @page("/", "app.jl.html")
    end
    """
    )
  end
end

end
